DOSKEY ls=dir
DOSKEY del=rm
DOSKEY c=cls
DOSKEY clear=cls
DOSKEY nrw=npm run webpack
DOSKEY nrs=npm run start
DOSKEY jamesroot=cd C:\Users\JEmbry\Developer\Freelancing\Test\JamesHenderson\root
DOSKEY finder=explorer
DOSKEY n=start cmd.exe
